server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/q_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: qwe461297538
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis: #redis配置
    host: 192.168.149.131
    port: 6379
    password: qwe461297538
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
#OSS配置
aliyun:
  oss:
    file:
      # 控制台 - oss - 点击对应桶 - 概览 - 地域节点
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t95yMJVtQtzFFyygzba
      keysecret: LBbeGdeK5jZnCC0XBDY55NZHSL6kfw
      bucketname: blog-qlt